### ISSUE TITLE
Install Vaadin framework

### ISSUE THREAD

**Issue by mntrq** [SSD2015/TeamMalee#4]

**Comment by jbrucker** [comment]
Installing some software is not an Issue.  Just do it.
You can delete this issue.

**Comment by dtinth** [comment]
On GitHub, you can't delete an issue, only close it. My suggestion is to name this issue something like “Install and setup Vaadin for eXceed Vote project,” so that it's not too trivial an issue anymore. After the task is finished, then close this issue.

In my opinion, I think any kind of task that blocks the progress of the project can be considered an issue. However, for this course, we prefer that your tasks are not too trivial and fine-grained like this. In the next iteration, please plan your tasks such that each task are not too small.

Each task should be completed within one day, but not too short (a task that takes about 30 minutes is good and keeps you motivating).

**Comment by dtinth** [comment]
Also, please note that some issues that doesn't make sense can be labelled with "invalid" and then closed immediately.

When closing an issue, please also always give a reason for closing it.

**Comment by naneen** [comment]
We have tried to install Vaadin for two days. We have faced a lot of conflicts, so we decided to close this issue and use Play framework instead.
